### PR TITLE
Integrate with AtomsBaseTesting

### PR DESCRIPTION
**Pull request by mfherbst**
Integrates with the AtomsBaseTesting package, which provides useful tools for testing downstream implementations of the AtomsBase interface like ExtXYZ. Essentially removes code duplication across packages such as ExtXYZ, AtomsIO, ASEconvert etc.

### CODE REVIEW

**Comment by jameskermode** [comment]
Thanks for the contribution. I’m happy to merge this, since it simply reduces duplication. Shall I do a release or is there more to come?

**Comment by mfherbst** [comment]
Thanks!

No need for a release IMO. It's just affecting testing code inside ExtXYZ.

**Comment by jameskermode** [comment]
Ok, I’ll do a patch release.

**Comment by mfherbst** [comment]
Perfect, thanks!

**Comment by jameskermode** [comment]
Done as v0.1.12 - but I saw a sporadic test failure, which looks to be related to numerical tolerance. Would you be able to take a look?

https://github.com/libAtoms/ExtXYZ.jl/actions/runs/4582555532/jobs/8092857287

**Comment by mfherbst** [comment]
Will do.

**Pull request merged**
