### PR TITLE
initial attempt at resolving problems with round-tripping isolated systems

### LINKED ISSUE #47: Saving isolated molecules to a file results a file that cannot be read
If you create isolated molecule with AtomsBase and save it using ExtXYZ and try to load the file

Here is a Working example:

```julia
using AtomsBase
using ExtXYZ
using Unitful

hydrogen = isolated_system([
        :H => [0, 0, 0.]u"Å",
        :H => [0, 0, 1.]u"Å"
])

ExtXYZ.save("example.xyz", hydrogen)

ExtXYZ.load("example.xyz")   # results in error
```

The saved file reads

```
2
pbc=[F, F, F] Lattice="inf 0.00000000 0.00000000 0.00000000 inf 0.00000000 0.00000000 0.00000000 inf" Properties=species:S:1:pos:R:3:velocities:R:3:Z:I:1
H         0.00000000       0.00000000       0.00000000         0.00000000       0.00000000       0.00000000          1
H         0.00000000       0.00000000       1.00000000         0.00000000       0.00000000       0.00000000          1
```

If you remove the lattice and pbc information from the file, then it works as intended.

 So, one fix would be to check, if structure has infinite bounding box, and if yes then just remove cell information from the save.

### PR DESCRIPTION
**Pull request by jameskermode**
Merging this PR will resolve #47

### CODE REVIEW

**Comment by tjjarvinen** [comment]
The issue seems to be with `AtomsBaseTesting.test_approx_eq`. It does not work for isolate systems that have infinite boundaries.

E.g. this fails

```julia
using AtomsBase
using AtomsBaseTesting
using Unitful

hydrogen = isolated_system([
    :H => [0, 0, 0.]u"Å",
    :H => [0, 0, 1.]u"Å"
])

test_approx_eq(hydrogen, hydrogen)
```

**Comment by cortner** [comment]
another case against using those infinities in AtomsBase.

**Comment by tjjarvinen** [comment]
New version of AtomsBaseTesting (v0.1.3) should have fixed this now.

Rerunning tests should now give pass for them now, and we can move forward with this PR.

**Comment by jameskermode** [comment]
thanks for the heads up! merging, then I'll tag a new release.

**Pull request merged**
